modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="enchantery"
version="1.1.1"
displayName="Enchantery"
displayURL="https://modrinth.com/mod/enchant_mod/"
logoFile="logo.png"
credits="MCreator"
authors="lavabucket72"
description="Adds various enchantments :lenny:"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.enchantery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration