modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="enchantery"
version="1.1.1"
displayName="Enchantery"
displayURL="https://modrinth.com/project/enchant_mod/"
logoFile="logo.png"
credits="MCreator"
authors="lavabucket72"
description="Adds various enchantments :lenny:"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.enchantery]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.enchantery]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration